export const eventsData = [
  {
    eventId: "463",
    eventName: "Savi Kahlon - Bombay High",
    displayLocation: "Bombay High Club, Pune",
    formatedDuration: "09 May | 3:00 PM",
    ticketPrice: "500",
    eventImageUrl:
      "https://app.ticketwings.in/assets/uploads/2504250150516201294.jpg",
    ageRestrict: "21",
    eventCategoryName: "Club",
    language: "Bollywood",
  },
  {
    eventId: "466",
    eventName: "MINIMAL ROOM Ft. Shaun",
    displayLocation: "BellaVista Cafe & Skybar, Nagpur",
    formatedDuration: "10 May | 8:00 PM",
    ticketPrice: "499",
    eventImageUrl:
      "https://app.ticketwings.in/assets/uploads/250429020147649957.jpg",
    ageRestrict: "21",
    eventCategoryName: "Club",
    language: "Techno",
  },
  // Add your existing events below or above this
  {
    eventId: "437",
    eventName: "Paradox Live Concert",
    ticketPrice: "700",
    currencyType: "₹",
    priceText: "Onwards",
    ageRestrict: "18",
    language: "Bollywood, Bollywood",
    location:
      "Anvita Farms- Best Wedding Lawn In Nagpur | Best Event Venue In Nagpur, Nagpur",
    displayLocation:
      "Anvita Farms, Opp. Jamtha Stadium, Besides Nayara Petrol Pump, Wardha Road, Nagpur.",
    eventCategoryName: "Concert",
    eventImageUrl:
      "https://app.ticketwings.in/assets/uploads/250419095449962786.jpg",
    description:
      "Star Nights proudly presents PARADOX LIVE – The Biggest Arena Show of the Summer! Featuring Paradox – The lyrical genius from MTV Hustle 2.0. More artists to be announced. May 4th at Anvita Farms, Nagpur. Be there!",
    formatedDuration: "04 May | 6:00 PM",
  },
  {
    eventId: "452",
    isAdmin: "0",
    vendorId: "14548",
    eventName: "Soul+ Breathe",
    ageRestrict: "All Ages",
    clubLayout: "",
    createdDate: "20-04-2025 18:47",
    currencyType: "₹",
    dayType: "0",
    description:
      "Soul+ Breathe: Kriya Shakti & Sound Healing\nJoin us for a 2-hour journey of breath, energy & sound on 17th May | 5–7 PM at Chitnavis Centre\nIncludes: gentle yogic stretches, Kriyā Āvāhan (invocation), Prāna Chālana (breathwork), energy embodiment & immersive sound healing.\nReconnect, realign & re-energize - from inside out!\nNote: All materials provided – just bring yourself!",
    displayLocation: "Chitnavis Centre, Nagpur",
    duration: "0hr 24 mins",
    durationMinutues: "1440",
    durationType: "2",
    eventCategoryId: "57",
    eventCategoryName: "Others",
    eventImageUrl:
      "https://app.ticketwings.in/assets/uploads/250420070146348493.jpg",
    eventName: "Soul+ Breathe",
    formateStartDateTime: "May 17 2025, 5:00 PM",
    priceText: "Onwards",
    startDateTime: "1747481400",
    status: "1",
    ticketPrice: "2,500",
    twCharges: "2",
    vendorId: "14518",
    formatedDuration: "18 May | 2:00 PM",
  },
  {
    eventId: "459",
    isAdmin: "0",
    vendorId: "15302",
    eventName: "Divine Xperience Festival",
    ageRestrict: "21",
    clubLayout: "",
    createdDate: "23-04-2025 22:05",
    currencyType: "₹",
    dayType: "1",
    description:
      "Divine Xperience is Back Again! This time even more bigger.\nBringing you a 2 days Techno Music Festival into the wild. Mind-blowing production & the same vibe. We’re doing it again !\nSee you all there to the madness.\n📅 7 -8 June 2025",
    displayLocation: "Tuli Suites, Sakoli Nagzira, Sakoli",
    duration: "0hr 2 mins",
    durationMinutues: "2880",
    durationType: "2",
    eventCategoryId: "88",
    eventCategoryName: "Festival",
    eventImageUrl:
      "https://app.ticketwings.in/assets/uploads/250427051552804749.jpg",
    eventName: "Divine Xperience Festival",
    formateStartDateTime: "Jun 07 2025, 4:00 PM",
    priceText: "Onwards",
    startDateTime: "1749292200",
    status: "1",
    ticketPrice: "4,000",
    twCharges: "2",
    vendorId: "15362",
    formatedDuration: "12 May | 5:00 PM",
  },
  {
    eventId: "473",
    eventName: "Savi Kahlon - Bombay High",
    displayLocation: "Bombay High Club, Pune",
    formatedDuration: "09 May | 8:00 PM",
    ticketPrice: "500",
    eventImageUrl:
      "https://app.ticketwings.in/assets/uploads/2504250150516201294.jpg",
    ageRestrict: "21",
    eventCategoryName: "Club",
    language: "Bollywood",
  },
  {
    eventId: "476",
    eventName: "MINIMAL ROOM Ft. Shaun",
    displayLocation: "BellaVista Cafe & Skybar, Nagpur",
    formatedDuration: "10 May | 8:00 PM",
    ticketPrice: "499",
    eventImageUrl:
      "https://app.ticketwings.in/assets/uploads/250429020147649957.jpg",
    ageRestrict: "21",
    eventCategoryName: "Club",
    language: "Techno",
  },
  // Add your existing events below or above this
  {
    eventId: "447",
    eventName: "Paradox Live Concert",
    ticketPrice: "700",
    currencyType: "₹",
    priceText: "Onwards",
    ageRestrict: "18",
    language: "Bollywood, Bollywood",
    location:
      "Anvita Farms- Best Wedding Lawn In Nagpur | Best Event Venue In Nagpur, Nagpur",
    displayLocation:
      "Anvita Farms, Opp. Jamtha Stadium, Besides Nayara Petrol Pump, Wardha Road, Nagpur.",
    eventCategoryName: "Concert",
    eventImageUrl:
      "https://app.ticketwings.in/assets/uploads/250419095449962786.jpg",
    description:
      "Star Nights proudly presents PARADOX LIVE – The Biggest Arena Show of the Summer! Featuring Paradox – The lyrical genius from MTV Hustle 2.0. More artists to be announced. May 4th at Anvita Farms, Nagpur. Be there!",
    formatedDuration: "04 May | 5:00 PM",
  },
  {
    eventId: "462",
    isAdmin: "0",
    vendorId: "14548",
    eventName: "Soul+ Breathe",
    ageRestrict: "All Ages",
    clubLayout: "",
    createdDate: "20-04-2025 18:47",
    currencyType: "₹",
    dayType: "0",
    description:
      "Soul+ Breathe: Kriya Shakti & Sound Healing\nJoin us for a 2-hour journey of breath, energy & sound on 17th May | 5–7 PM at Chitnavis Centre\nIncludes: gentle yogic stretches, Kriyā Āvāhan (invocation), Prāna Chālana (breathwork), energy embodiment & immersive sound healing.\nReconnect, realign & re-energize - from inside out!\nNote: All materials provided – just bring yourself!",
    displayLocation: "Chitnavis Centre, Nagpur",
    duration: "0hr 24 mins",
    durationMinutues: "1440",
    durationType: "2",
    eventCategoryId: "57",
    eventCategoryName: "Others",
    eventImageUrl:
      "https://app.ticketwings.in/assets/uploads/250420070146348493.jpg",
    eventName: "Soul+ Breathe",
    formateStartDateTime: "May 17 2025, 5:00 PM",
    priceText: "Onwards",
    startDateTime: "1747481400",
    status: "1",
    ticketPrice: "2,500",
    twCharges: "2",
    vendorId: "13548",
    formatedDuration: "20 May | 4:00 PM",
  },
  {
    eventId: "469",
    isAdmin: "0",
    vendorId: "15312",
    eventName: "Divine Xperience Festival",
    ageRestrict: "21",
    clubLayout: "",
    createdDate: "23-04-2025 22:05",
    currencyType: "₹",
    dayType: "1",
    description:
      "Divine Xperience is Back Again! This time even more bigger.\nBringing you a 2 days Techno Music Festival into the wild. Mind-blowing production & the same vibe. We’re doing it again !\nSee you all there to the madness.\n📅 7 -8 June 2025",
    displayLocation: "Tuli Suites, Sakoli Nagzira, Sakoli",
    duration: "0hr 2 mins",
    durationMinutues: "2880",
    durationType: "2",
    eventCategoryId: "88",
    eventCategoryName: "Festival",
    eventImageUrl:
      "https://app.ticketwings.in/assets/uploads/250427051552804749.jpg",
    eventName: "Divine Xperience Festival",
    formateStartDateTime: "Jun 07 2025, 4:00 PM",
    priceText: "Onwards",
    startDateTime: "1749292200",
    status: "1",
    ticketPrice: "4,000",
    twCharges: "2",
    vendorId: "15302",
    formatedDuration: "25 May | 1:00 PM",
  },
  {
    eventId: "483",
    eventName: "Savi Kahlon - Bombay High",
    displayLocation: "Bombay High Club, Pune",
    formatedDuration: "09 May | 8:00 PM",
    ticketPrice: "500",
    eventImageUrl:
      "https://app.ticketwings.in/assets/uploads/2504250150516201294.jpg",
    ageRestrict: "21",
    eventCategoryName: "Club",
    language: "Bollywood",
  },
  {
    eventId: "486",
    eventName: "MINIMAL ROOM Ft. Shaun",
    displayLocation: "BellaVista Cafe & Skybar, Nagpur",
    formatedDuration: "10 May | 7:00 PM",
    ticketPrice: "499",
    eventImageUrl:
      "https://app.ticketwings.in/assets/uploads/250429020147649957.jpg",
    ageRestrict: "21",
    eventCategoryName: "Club",
    language: "Techno",
  },
];
